name: Run Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.MY_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.MY_AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: "us-east-1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-Line script
        run: |
         echo my access key id  ${{ secrets.MY_AWS_ACCESS_KEY_ID }}
         echo my secret access key id ${{ secrets.MY_AWS_SECRET_ACCESS_KEY }}